#!/usr/bin/env bash
# Configures a new Ubuntu machine by installing Nginx, setting up a custom 404 page, and configuring a redirect.

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
         sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# Starting nginx service
sudo service nginx start

# Allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating new index
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

# Setting up /redirect_me to a YouTube video
sudo sed -i '/server_name _;/a\\n    location /redirect_me {\n        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n    }\n' /etc/nginx/sites-available/default

# Set up a 404 page
echo "Ceci n'est pas une page" > /var/www/html/error_404.html
sudo sed -i '/server_name _;/a\\n    error_page 404 /error_404.html;\n' /etc/nginx/sites-available/default

# Restarting nginx
sudo service nginx restart
