#!/usr/bin/env bash
# Check if an argument is provided

if [[ $1 =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]
then
	ping -c 5 "$1"
else
	echo "usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
