#!/usr/bin/env bash
sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo service nginx status | grep -q "not running" && echo "" | sudo dd status=none of=/run/nginx.pid

